name: Update Progress

on:
  push:
    branches:
      - main
      - master

jobs:
  sync-progress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run Sync Script
        run: python sync_progress.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "🔄 Auto-update progress [skip ci]" || echo "No changes"
          git push
